### ISSUE TITLE
Determining Tumblr Endpoints

### ISSUE THREAD

**Issue by venegu** [Soother/Soothe#11]
You will need to figure out what endpoints and what data we will need fetch. Please post this information here. 

Additionally, create a mini example with a table view that displays post with an image and a post with just text of some sort (no auto layout necessary) to a repo of your own. The reason being is that sometimes it's easier to implement complex things in a clean project then move it into a more complex project.

**Comment by NashidC** [comment]
**Endpoints:**
Request-token URL
https://www.tumblr.com/oauth/request_token
Authorize URL
https://www.tumblr.com/oauth/authorize
Access-token URL
https://www.tumblr.com/oauth/access_token

**OAuth Consumer Key:**
Adr6aijLvyfq23Ja9RlBJosYeKcH571UWDajh05IM7QbnR1vYm



So since we are only going to use text and photo posts:
_Text post retrieval:_ https://api.tumblr.com/v2/blog/citriccomics.tumblr.com/posts/text?api_key={key}

_Photo Post retrieval:_ https://api.tumblr.com/v2/blog/derekg.org/posts?id=7431599279&api_key={key}

File including example code (code is written in obj-c, not sure why but yeah)
