### ISSUE TITLE
W[6] - Submitting Data Schema

### ISSUE THREAD

**Issue by venegu** [Soother/Soothe#31]
As we do not plan on using Parse, we do not have a data schema, but we listed the APIs and endpoints we plan on getting in issue #8, #10 and #11. I will add these to the README or the wiki directly in a bit.

/cc @codepathreview

**Comment by avo1** [comment]
:+1: Nice work on getting the endpoints defined (instead of the schema)! Next week we jump into the first implementation sprint. You'll have 3 sprints (one week each) to complete all the required stories for your app and 2 sprints (one week each) to work on optionals and add polish. Let us know if we can help in any way!
